"""Shared constants for the executive Cosan dashboard."""

COSAN_CNPJ = "50.746.577/0001-15"
COSAN_NAME = "COSAN S.A."
COSAN_SETOR = "Agricultura (Açúcar, Álcool e Cana)"

PRIORITY_INDICATORS = [
    {
        "group": "Liquidez",
        "code": "LIQ_SECA_AJUSTADA",
        "label": "Liquidez Seca Ajustada",
        "direction": "higher_better",
        "format": "ratio",
    },
    {
        "group": "Liquidez",
        "code": "LIQ_CORRENTE",
        "label": "Liquidez Corrente",
        "direction": "higher_better",
        "format": "ratio",
    },
    {
        "group": "Liquidez",
        "code": "LIQ_IMEDIATA",
        "label": "Liquidez Imediata",
        "direction": "higher_better",
        "format": "ratio",
    },
    {
        "group": "Endividamento",
        "code": "ENDIV_TOTAL",
        "label": "Endividamento Total",
        "direction": "lower_better",
        "format": "pct",
    },
    {
        "group": "Endividamento",
        "code": "COMPOSICAO_ENDIV",
        "label": "Composicao do Endividamento",
        "direction": "lower_better",
        "format": "pct",
    },
    {
        "group": "Endividamento",
        "code": "GARANTIA_CP_CT",
        "label": "Garantia Capital Proprio / Capital de Terceiros",
        "direction": "higher_better",
        "format": "ratio",
    },
    {
        "group": "Margens",
        "code": "MARGEM_BRUTA",
        "label": "Margem Bruta",
        "direction": "higher_better",
        "format": "pct",
    },
    {
        "group": "Margens",
        "code": "MARGEM_OPERACIONAL",
        "label": "Margem Operacional",
        "direction": "higher_better",
        "format": "pct",
    },
    {
        "group": "Margens",
        "code": "MARGEM_LIQUIDA",
        "label": "Margem Liquida",
        "direction": "higher_better",
        "format": "pct",
    },
    {
        "group": "Rentabilidade",
        "code": "ROA",
        "label": "ROA",
        "direction": "higher_better",
        "format": "pct",
    },
    {
        "group": "Rentabilidade",
        "code": "ROE",
        "label": "ROE",
        "direction": "higher_better",
        "format": "pct",
    },
    {
        "group": "Rentabilidade",
        "code": "ROI",
        "label": "ROI",
        "direction": "higher_better",
        "format": "pct",
    },
    {
        "group": "Atividade",
        "code": "GIRO_ESTOQUES_AJUSTADO",
        "label": "Giro de Estoques Ajustado",
        "direction": "higher_better",
        "format": "ratio",
    },
    {
        "group": "Atividade",
        "code": "PMRE_AJUSTADO",
        "label": "PMRE Ajustado",
        "direction": "lower_better",
        "format": "days",
    },
    {
        "group": "Atividade",
        "code": "PMRV",
        "label": "PMRV",
        "direction": "lower_better",
        "format": "days",
    },
    {
        "group": "Atividade",
        "code": "PMPC",
        "label": "PMPC",
        "direction": "higher_better",
        "format": "days",
    },
    {
        "group": "Ciclos",
        "code": "CICLO_ECONOMICO",
        "label": "Ciclo Economico",
        "direction": "lower_better",
        "format": "days",
    },
    {
        "group": "Ciclos",
        "code": "CICLO_FINANCEIRO",
        "label": "Ciclo Financeiro",
        "direction": "lower_better",
        "format": "days",
    },
    {
        "group": "Recursos Financeiros",
        "code": "NCG",
        "label": "Necessidade de Capital de Giro",
        "direction": "lower_better",
        "format": "currency",
    },
    {
        "group": "Recursos Financeiros",
        "code": "ST",
        "label": "Saldo de Tesouraria",
        "direction": "higher_better",
        "format": "currency",
    },
    {
        "group": "Recursos Financeiros",
        "code": "CGL",
        "label": "Capital de Giro Liquido",
        "direction": "higher_better",
        "format": "currency",
    },
]

PRIORITY_INDICATOR_CODES = [item["code"] for item in PRIORITY_INDICATORS]
INDICATOR_META = {item["code"]: item for item in PRIORITY_INDICATORS}

IPRF_INDICATORS = [
    {
        "dimension": "Liquidez",
        "code": "LIQ_CORRENTE",
        "note_code": "NOTA_LIQ_CORRENTE",
        "label": "Liquidez Corrente",
        "direction": "higher_better",
        "format": "ratio",
    },
    {
        "dimension": "Liquidez",
        "code": "LIQ_SECA_AJUSTADA",
        "note_code": "NOTA_LIQ_SECA",
        "label": "Liquidez Seca Ajustada",
        "direction": "higher_better",
        "format": "ratio",
    },
    {
        "dimension": "Liquidez",
        "code": "COB_CAIXA_OPERACIONAL",
        "note_code": "NOTA_COB_CAIXA_OPERACIONAL",
        "label": "Cobertura de Caixa Operacional",
        "direction": "higher_better",
        "format": "ratio",
    },
    {
        "dimension": "Rentabilidade",
        "code": "MARGEM_EBITDA",
        "note_code": "NOTA_MARGEM_EBITDA",
        "label": "Margem EBITDA",
        "direction": "higher_better",
        "format": "pct",
    },
    {
        "dimension": "Rentabilidade",
        "code": "MARGEM_LIQUIDA",
        "note_code": "NOTA_MARGEM_LIQUIDA",
        "label": "Margem Liquida",
        "direction": "higher_better",
        "format": "pct",
    },
    {
        "dimension": "Rentabilidade",
        "code": "ROA",
        "note_code": "NOTA_ROA",
        "label": "ROA",
        "direction": "higher_better",
        "format": "pct",
    },
    {
        "dimension": "Solvencia",
        "code": "DL_EBITDA",
        "note_code": "NOTA_DL_EBITDA",
        "label": "Divida Liquida / EBITDA",
        "direction": "lower_better",
        "format": "ratio",
    },
    {
        "dimension": "Solvencia",
        "code": "GRAU_ENDIVIDAMENTO",
        "note_code": "NOTA_GRAU_ENDIVIDAMENTO",
        "label": "Grau de Endividamento",
        "direction": "lower_better",
        "format": "pct",
    },
    {
        "dimension": "Eficiencia",
        "code": "CCC",
        "note_code": "NOTA_CCC",
        "label": "Ciclo de Conversao de Caixa",
        "direction": "lower_better",
        "format": "days",
    },
    {
        "dimension": "Eficiencia",
        "code": "GIRO_ATIVO_TOTAL",
        "note_code": "NOTA_GIRO_ATIVO_TOTAL",
        "label": "Giro do Ativo Total",
        "direction": "higher_better",
        "format": "ratio",
    },
    {
        "dimension": "Geracao de Caixa",
        "code": "MARGEM_CAIXA_OPERACIONAL",
        "note_code": "NOTA_MARGEM_CAIXA_OPERACIONAL",
        "label": "Margem de Caixa Operacional",
        "direction": "higher_better",
        "format": "pct",
    },
    {
        "dimension": "Geracao de Caixa",
        "code": "COBERTURA_DIVIDA_CAIXA",
        "note_code": "NOTA_COBERTURA_DIVIDA_CAIXA",
        "label": "Cobertura de Divida por Caixa",
        "direction": "higher_better",
        "format": "ratio",
    },
    {
        "dimension": "Geracao de Caixa",
        "code": "INTENSIDADE_REINVESTIMENTO",
        "note_code": "NOTA_INTENSIDADE_REINVESTIMENTO",
        "label": "Intensidade de Reinvestimento",
        "direction": "u_shape",
        "format": "pct",
    },
]

IPRF_DIMENSION_SCORES = [
    ("SCORE_LIQUIDEZ", "Liquidez"),
    ("SCORE_RENTABILIDADE", "Rentabilidade"),
    ("SCORE_SOLVENCIA", "Solvencia"),
    ("SCORE_EFICIENCIA", "Eficiencia"),
    ("SCORE_GERACAO_CAIXA", "Geracao de Caixa"),
]

COSAN_COLORS = {
    "bg": "#091929",
    "card": "#112236",
    "card_alt": "#0D2137",
    "line": "#1E3A55",
    "text": "#F6FBFF",
    "muted": "#7DA5BE",
    "lime": "#B5E300",
    "teal": "#00AEBA",
    "amber": "#F59E0B",
    "red": "#EF4444",
    "violet": "#A78BFA",
    "green": "#34D399",
}
